# Generated by Django 3.1.7 on 2021-03-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField(blank=True, max_length=10000, null=True)),
                ('goal', models.CharField(max_length=150)),
                ('date', models.TextField(max_length=100)),
            ],
        ),
    ]
